version: "3.9"
services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: events
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Api/Dockerfile
    depends_on:
      - db
    environment:
      # line breaks = "__" in ASP.NET configuration binding
      CONNECTIONSTRINGS__EVENTS: "Host=db;Port=5432;Database=events;Username=postgres;Password=postgres"
    ports:
      - "8080:8080"

volumes:
  pgdata:
